version: '3'

services:

        web:
                build: .
                command: python -u flask_brevets.py
                ports:
                        - "5003:5000"
                depends_on:
                        - db
                environment:
                        MONGO_HOSTNAME: db
        db:
                image: mongo:latest
